README.md
initworkspace
monke.patch

Updates `monke.patch` to support the newest 10.1.0 version of the twitch app
Closes #12

Update to v10.1.0

---

README.md
buildsource
genmonke
genmonkefull
genmonkeonly
initworkspace

Closes #11 by adding a new script called `genmonkefull`

genmonkefull

---

.dockerignore
Dockerfile
README.md
buildsource
initworkspace

Closes #16 by adding a Dockerfile whch is published as [bttv-android-builder](https://hub.docker.com/r/fosefx/bttv-android-builder) on the docker hub

Add Dockerfile

---

monke.patch
source/bttv/ChatMessageDeligateWrapper.java
source/bttv/Emote.java
source/bttv/EmoteCardUtil.java
source/io/reactivex/Single.java
source/tv/twitch/android/shared/chat/model/EmoteCardModel.java
source/tv/twitch/android/shared/chat/parser/EmoteCardModelParser.java

Adds bttv on press handler

---

monke.patch

Remove trailing whitespace

---

monke.patch
source/bttv/ChatMessageDelegateWrapper.java
source/bttv/ChommentModelDelegateWrapper.java
source/bttv/Data.java
source/bttv/EmoteUrlUtil.java
source/bttv/Tokenizer.java
source/tv/twitch/android/models/channel/ChannelModel.java
source/tv/twitch/android/models/chomments/ChommentModel.java
source/tv/twitch/android/shared/chat/ChatMessageDelegate.java
source/tv/twitch/android/shared/chat/ChatMessageParser.java
source/tv/twitch/android/shared/chat/chomments/ChommentModelDelegate.java
source/tv/twitch/chat/ChatMessageInfo.java

Tested for vods and clips
Fixes #30

Add emotes to chat replay

---

.github/workflows/build.yml
.gitignore
Dockerfile
README.md
disassemble
initworkspace
monke.patch
source/bttv/Data.java

CHANGELOG
- bump base to 10.3.1

v0.1.0-beta

---

.github/workflows/build.yml
README.md
monke.patch
source/bttv/Data.java

Update base to v10.5.0

---

.github/workflows/build.yml
README.md
monke.patch
source/bttv/Data.java

Update base to v10.6.0

---

.dockerignore
.github/workflows/build.yml
.github/workflows/docker.yml
Dockerfile
README.md

Remove source and monke.patch from docker image

---

README.md
mod/app/src/main/java/bttv/Data.java
monke.patch

Bump base to v10.7.0

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
buildsource
initworkspace
monke.patch

Update base to v10.8.0

---

CHANGELOG.md
buildsource
initworkspace
monke.patch

Fix crash caused by missing bttv classes

---

mod/app/src/main/java/bttv/ChannelPoints.java
mod/app/src/main/java/bttv/settings/SettingsPresenter.java
mod/app/src/main/java/bttv/settings/UserPreferences.java
monke.patch

Auto-Claim Bonus Channel Points

---

mod/app/src/main/java/bttv/SleepTimer.java
mod/app/src/main/java/bttv/Util.java
mod/app/src/main/java/bttv/settings/SettingsPresenter.java
mod/app/src/main/java/bttv/settings/UserPreferences.java
mod/app/src/main/res/drawable/bttv_ic_bedtime.xml
monke.patch

Sleep timer

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
monke.patch

Base update 10.9.1

---

README.md
mod/app/src/main/java/bttv/Data.java
mod/app/src/main/java/bttv/Network.java
mod/app/src/main/java/bttv/Tokenizer.java
mod/app/src/main/java/bttv/emote/ChannelEmoteData.java
mod/app/src/main/java/bttv/emote/Emote.java
mod/app/src/main/java/bttv/emote/EmoteCardUtil.java
mod/app/src/main/java/bttv/emote/EmotePicker.java
mod/app/src/main/java/bttv/emote/EmoteUrlUtil.java
mod/app/src/main/java/bttv/emote/Emotes.java
mod/app/src/main/java/bttv/settings/SettingsPresenter.java
mod/app/src/main/java/bttv/settings/UserPreferences.java
mod/app/src/test/java/bttv/mod/RetokenizeTest.java
mod/app/src/test/java/bttv/mod/TokenizerTest.java
monke.patch

Add 7TV support

---

CHANGELOG.md
mod/app/src/main/java/bttv/updater/UpdaterJobService.java

Periodic update check gets scheduled too often

---

mod/app/src/main/java/bttv/ChannelPoints.java
mod/app/src/main/java/bttv/SleepTimer.java
mod/app/src/main/java/bttv/Tokenizer.java
mod/app/src/main/java/bttv/Util.java
mod/app/src/main/java/bttv/emote/Emotes.java
mod/app/src/main/java/bttv/settings/Settings.java
mod/app/src/main/java/bttv/settings/SettingsPresenter.java
mod/app/src/main/java/bttv/settings/UserPreferences.java
mod/app/src/main/java/bttv/settings/abstractions/Switch.java
mod/app/src/main/res/values/strings.xml
mod/app/src/test/java/bttv/mod/TokenizerTest.java

Refactor Settings

---

CHANGELOG.md
monke.patch

Tokenize sub messages

---

buildsource
initworkspace
mod/app/src/main/java/bttv/Credits.java
mod/app/src/main/java/bttv/Res.java
mod/app/src/main/java/bttv/settings/Settings.java
mod/app/src/main/java/bttv/settings/SettingsPresenter.java
mod/app/src/main/res/layout/bttv_credits_dialog.xml
mod/app/src/main/res/values/strings.xml
mod/twitch/src/main/java/tv/twitch/android/models/settings/SettingsDestination.java
monke.patch

Fixes #131 
- adds credits dialog

Add Credits

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
monke.patch

Fixes #224 
- update base to v11.3.0 of the twitch app

Update to v11.3.0

---

CHANGELOG.md
mod/app/src/main/java/bttv/Data.java
mod/app/src/main/java/bttv/Res.java
mod/app/src/main/java/bttv/SubscribeRedirect.java
mod/app/src/main/java/bttv/api/Glide.java
mod/app/src/main/java/bttv/api/SubscribeRedirect.java
mod/app/src/main/res/values/strings.xml
mod/twitch/src/main/java/tv/twitch/android/models/social/ChatUser.java
mod/twitch/src/main/java/tv/twitch/android/shared/chat/chatuserdialog/ChatUserDialogInfo.java
mod/twitch/src/main/java/tv/twitch/android/shared/chat/chatuserdialog/ChatUserDialogPresenter.java
monke.patch

Gift subs redirect to web page

---

CHANGELOG.md
mod/app/src/main/java/bttv/Tokenizer.java
mod/app/src/test/java/bttv/mod/RetokenizeTest.java
mod/app/src/test/java/bttv/mod/TokenizerTest.java

Adding back spaces between emotes

---

CHANGELOG.md
mod/app/src/main/java/bttv/Res.java
mod/app/src/main/java/bttv/ResUtil.java
mod/app/src/main/java/bttv/SplitChat.java
mod/app/src/main/java/bttv/api/SplitChat.java
mod/app/src/main/java/bttv/settings/Settings.java
mod/app/src/main/res/values/strings.xml
mod/twitch/src/main/java/tv/twitch/android/adapters/social/MessageRecyclerItem.java
mod/twitch/src/main/java/tv/twitch/android/core/adapters/RecyclerAdapterItem.java
patches/res.values.public.xml.patch
patches/tv.twitch.android.app.consumer.TwitchApplication.smali.patch
patches/tv.twitch.android.core.adapters.TwitchAdapter.smali.patch

Fixes #195 
- add split chat feature

Add Split Chat Feature

---

CHANGELOG.md
mod/app/src/main/java/bttv/ChommentModelDelegateWrapper.java
mod/app/src/main/java/bttv/Tokenizer.java
mod/app/src/main/java/bttv/highlight/Highlight.java
mod/app/src/test/java/bttv/mod/TokenizerTest.java

Highlight VODs

---

.github/workflows/ci.yml
CHANGELOG.md
mod/app/src/main/java/bttv/SplitChat.java
mod/twitch/src/main/java/tv/twitch/android/shared/chat/adapter/item/MessageRecyclerItem.java
patches/tv.twitch.android.app.consumer.dagger.DaggerAppComponent$SettingsActivitySubcomponentImpl.smali.patch
patches/tv.twitch.android.app.consumer.dagger.DaggerAppComponent.smali.patch
patches/tv.twitch.android.shared.chat.adapter.ChannelChatAdapter.smali.patch
patches/tv.twitch.android.shared.chat.messagefactory.ChatMessageFactory.smali.patch
patches/tv.twitch.android.shared.chat.util.ChatUtil$Companion.smali.patch

Update to v12.1.2

---

.github/workflows/ci.yml
.gitignore
README.md
disassemble
initworkspace

Cache disass

---

CHANGELOG.md
mod/app/src/main/java/bttv/Tokenizer.java
mod/app/src/test/java/bttv/mod/RetokenizeTest.java
mod/app/src/test/java/bttv/mod/TokenizerTest.java
mod/twitch/src/main/java/tv/twitch/android/models/chat/MessageToken.java
mod/twitch/src/main/java/tv/twitch/chat/ChatMentionToken.java
mod/twitch/src/main/java/tv/twitch/chat/ChatUrlToken.java

Fixes #393 
- add unit tests
- fix bug

fix url-after-mention missing space

---

CHANGELOG.md
genmonke
mod/app/src/main/java/bttv/Res.java
mod/app/src/main/java/bttv/api/SettingsBottom.java
mod/app/src/main/java/bttv/settings/SettingsBottom.java
mod/app/src/main/java/bttv/settings/abstractions/bottom/Toggle.java
mod/twitch/src/main/java/tv/twitch/android/core/mvp/viewdelegate/IEventDispatcher.java
mod/twitch/src/main/java/tv/twitch/android/core/mvp/viewdelegate/RxViewDelegate.java
mod/twitch/src/main/java/tv/twitch/android/core/mvp/viewdelegate/ViewDelegateEvent.java
mod/twitch/src/main/java/tv/twitch/android/core/mvp/viewdelegate/ViewDelegateState.java
mod/twitch/src/main/java/tv/twitch/android/shared/ui/menus/togglemenu/SimpleToggleRowViewDelegate.java
patches/res.values.public.xml.patch
patches/settings-bottom/res.layout-v22.chat_settings_bottom_sheet.xml.patch
patches/settings-bottom/res.layout.chat_settings_bottom_sheet.xml.patch
patches/settings-bottom/tv.twitch.android.shared.chat.settings.entry.ChatSettingsViewDelegate.smali.patch

Fixes #412 
- add subset of settings to bottom settings sheet

Bottom settings

---

mod/app/src/main/java/bttv/Res.java
mod/app/src/main/java/bttv/ResUtil.java
mod/app/src/main/java/bttv/settings/SettingsBottom.java
mod/app/src/main/java/bttv/settings/abstractions/bottom/Link.java
mod/app/src/main/java/bttv/settings/abstractions/bottom/Toggle.java
mod/twitch/src/main/java/tv/twitch/android/shared/ui/menus/infomenu/InfoMenuViewDelegate.java

Related to #444 
- add anon toggle
- add open highlights button

Add more settings to bottom chat settings

---

CHANGELOG.md
mod/app/src/main/java/bttv/Res.java
mod/app/src/main/java/bttv/Tokenizer.java
mod/app/src/main/java/bttv/api/Blacklist.java
mod/app/src/main/java/bttv/highlight/Blacklist.java
mod/app/src/main/java/bttv/highlight/Highlight.java
mod/app/src/main/java/bttv/highlight/StringSetUI.java
mod/app/src/main/java/bttv/highlight/StringSetUIAdapter.java
mod/app/src/main/java/bttv/settings/Settings.java
mod/app/src/main/java/bttv/settings/SettingsBottom.java
mod/app/src/main/java/bttv/settings/SettingsPresenter.java
mod/app/src/main/java/bttv/settings/StreamSettings.java
mod/app/src/main/res/layout/bttv_blacklist_dialog.xml
mod/app/src/main/res/layout/bttv_stream_settings.xml
mod/app/src/main/res/values/strings.xml
mod/twitch/src/main/java/tv/twitch/android/models/settings/SettingsDestination.java
patches/emotes/tv.twitch.android.shared.chat.messagefactory.ChatMessageFactory.smali.patch
patches/res.values.public.xml.patch
patches/settings/tv.twitch.android.models.settings.SettingsDestination.smali.patch

Add Blacklist

---

CHANGELOG.md
genmonke
mod/app/src/main/java/bttv/api/SleepTimer.java
mod/twitch/src/main/java/tv/twitch/android/shared/player/overlay/RxBottomPlayerControlOverlayViewDelegate.java
mod/twitch/src/main/java/tv/twitch/android/shared/player/overlay/databinding/BottomPlayerOverlayControlsBinding.java
patches/sleeptimer/res.layout-v22.bottom_player_overlay_controls.xml.patch
patches/sleeptimer/res.layout.bottom_player_overlay_controls.xml.patch
patches/sleeptimer/tv.twitch.android.shared.player.overlay.RxBottomPlayerControlOverlayViewDelegate.smali.patch
patches/sleeptimer/tv.twitch.android.shared.player.overlay.databinding.BottomPlayerOverlayControlsBinding.smali.patch

Fixes #571 
* add back sleep timer to livestreams

Fix sleep timer

---

README.md

Fix issue in README

---

CHANGELOG.md
patches/subs/tv.twitch.android.shared.chat.chatuserdialog.ChatUserDialogPresenter.smali.patch

fix View Info button
